### ISSUE TITLE
Proper description for collateral, underlying, strike

### ISSUE THREAD

**Issue by aparnakr** [opynfinance/GammaProtocol#21]
Update all the comments with proper descriptions for collateral, underlying and strike.

**Comment by haythem96** [comment]
From Andrew comment:
 * @param _underlyingAsset asset that the option references
 * @param _strikeAsset asset that the strike price is denominated in
 * @param _collateralAsset asset that is held as collateral against short/written options
 * @param _strikePrice strike price with decimals = 18
 * @param _isPut is this a put option, if not it is a call
