### ISSUE TITLE
Functional tests for oToken + oTokenFactory

### ISSUE THREAD

**Issue by aparnakr** [opynfinance/GammaProtocol#28]

**Comment by antoncoding** [comment]
Should include the following tests:
* test all the Factory methods with A real AddressBook instance providing a real Otoken implementation.
* test all the methods on Otokens for instances that are created by the Factory.

**Comment by haythem96** [comment]
@antoncoding what's the difference between the `Otoken.test.ts` and the tests for "test all the methods on Otokens for instances that are created by the Factory." ?

**Comment by antoncoding** [comment]
In `Otoken.test.ts`, you test the otoken instance by 
```
const otoken = Otoken.new()
```
In functional test, the instances is created by 
```
const otoken = Otoken.createOtoken()
```

**Comment by haythem96** [comment]
> In `Otoken.test.ts`, you test the otoken instance by
> 
> ```
> const otoken = Otoken.new()
> ```
> 
> In functional test, the instances is created by
> 
> ```
> const otoken = Otoken.createOtoken()
> ```

Yeah but it is the same instance, right ? from the same deployed contract, so technically they are the same.

**Comment by antoncoding** [comment]
no, with  `Otoken.new()` you deploy a new Otoken instance. with `Factory.createOtoken` you deploy a minimal proxy and point that to the deployed Otoken contract.
