### ISSUE TITLE
Remove AddressBook from MarginCalculator

### ISSUE THREAD

**Issue by haythem96** [opynfinance/GammaProtocol#333]
Remove `addressBook` storage variable from `MarginCalculator.sol` and set `Oracle` address in the constructor level.

**Comment by antoncoding** [comment]
can't we use the same pattern as Controller instead? I think this somehow conflicts with the AddressBook design we had.

**Comment by haythem96** [comment]
> can't we use the same pattern as Controller instead? I think this somehow conflicts with the AddressBook design we had.

Yes we can, but as this module can easily be replaced, I don't think it should follow the same design.
I avoided the Controller pattern (using the refresh configuration function) just to avoid the need for an owner address to Calculator also.

**Comment by antoncoding** [comment]
okay with that, just think the refresh was cool and not necessarily need an admin 😂

**Comment by haythem96** [comment]
Done #338
