### ISSUE TITLE
Refactor MarginCalculator external calls to Otoken contract

### ISSUE THREAD

**Issue by haythem96** [opynfinance/GammaProtocol#337]
The `MarginCalculator.sol` contract execute a lot of external calls to Otoken.sol to fetch vault details (short token strike, short token strike asset...etc). Such repetitive calls consume a lot of gas.
Some external calls that are repeating along the Calculator execution are:
- getting short otoken collateral, underlying, strike asset and type.
- getting long otoken collateral, underlying, strike asset and type

I suggest having one function in the beginning of `getExcessCollateral()` that take a vault as arg and return the vault details in a struct that can be used for the rest of the execution logic:
```
struct VaultDetails {
  address shortUnderlying;
  address shortStrike;
  address shortCollateral;
  address shortStrikePrice;
  address longUnderlying;
  address longStrike;
  address longCollateral;
  address longStrikePrice;
  uint256 shortDecimals;
  uint256 longDecimals;
  uint256 collateralDecimals
}
```

**Comment by aparnakr** [comment]
Good with that.

**Comment by haythem96** [comment]
Done.
