### ISSUE TITLE
Remove FixedPointInt256 library from YearnPricer

### ISSUE THREAD

**Issue by haythem96** [opynfinance/GammaProtocol#413]
`YearnPricer` does not use `FixedPointInt256` library. Will be better to remove the import statement.

**Comment by ladybando** [comment]
I removed the import statement, but am unable to add the new branch I created.

**Comment by haythem96** [comment]
> I removed the import statement, but am unable to add the new branch I created.

That's awesome. I think you should fork this repository, push the changes to your fork, and them make a pull request from there. 
This link can help https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by haythem96** [comment]
Closing this as it is solved.
