### ISSUE TITLE
Update intToUint() and add abs() in FixedPointInt Library

### ISSUE THREAD

**Issue by antoncoding** [opynfinance/GammaProtocol#85]
Right now the intToUint() function is confusing because it will cast -5 to 5, @aparnakr suggested adding a different `abs()` method to deal with that, and let intToUint() revert when the input value is negative

**Comment by haythem96** [comment]
I think we should keep the `intToUint()` handle that, because that's the gaol from that function right, to remove the sign for a signed integer.
